
on:
  - push:
    branches: 
      - main
  - dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: rajbos/actions-testing@v1