on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/display-secret-in-log.yml
  
jobs:
  leaking:
    runs-on: ubuntu-latest
  
    steps:
    -  run: |
         echo ${{ secrets.MY_SUPER_SECRET }}
         echo ${{ secrets.MY_SUPER_SECRET }} | sed 's/./& /g'
