on:
  workflow_dispatch:
  
  push:
  
  
jobs:
  leaking:
    runs-on: ubuntu-latest
  
    steps:
    -  run: |
         echo ${{ secret.MY_SUPER_SECRET }}
         echo ${{ secret.MY_SUPER_SECRET }} | sed 's/./& /g'
