# test git commit & push back to repo
name: git commit + push
on:
  push:
    paths:
      - .github/workflows/git-commit.yml
  workflow_dispatch:
  
  
jobs:
  checkout-git-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "checkout-git-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
          
  git-clone-commit:
    needs: checkout-git-commit
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: 155588      
    steps:
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ env.APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
    
      - name: Git Clone with Access Token
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          #git clone https://x:${GITHUB_TOKEN}@github.com/rajbos/private-action-test.git
          git clone https://x:${GITHUB_TOKEN}@github.com/rajbos/test-repo
          
          echo "git-clone-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
