# test git commit & push back to repo
name: git commit + push
on:
  push:
    paths:
      - .github/workflows/git-commit.yml
  workflow_dispatch:
  
  
jobs:
  checkout-git-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "checkout-git-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
          
  git-clone-commit:
    needs: checkout-git-commit
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/rajbos/private-action-test.git
          
          echo "git-clone-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
