# test git commit & push back to repo with various options (check each job)
name: git commit + push
on:
  push:
    paths:
      - .github/workflows/git-commit.yml
  workflow_dispatch:
  
  
jobs:
  checkout-git-commit:
    # run the normal checkout action and use that to make commits and push back using the GITHUB_TOKEN
    # more info on access tokens here: https://devopsjournal.io/blog/2022/01/03/GitHub-Tokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "checkout-git-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
          
          
          
  git-clone-commit:
    # run a manual checkout action with an access token from a GitHub App
    # more info on access tokens here: https://devopsjournal.io/blog/2022/01/03/GitHub-Tokens
    needs: checkout-git-commit
    runs-on: ubuntu-latest  
    steps:
    
      - name: Get Access Token for the linked GitHub App
        id: get_workflow_token
        env:
          APPLICATION_ID: 155588      
        uses: peter-murray/workflow-application-token-action@e8782d687a306fb13d733244d0f2a50e272d3752
        with:
          application_id: ${{ env.APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
    
      - name: Git Clone with Access Token
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          git clone https://x:${GITHUB_TOKEN}@github.com/rajbos/test-repo
          cd test-repo
          
          echo "git-clone-commit $(date +%Y%m%d_%H%M%S)" >> temp/datetime.txt

          git config user.email "bot@github.com"
          git config user.name "bot@github.com"
          
          git add .
          git commit -m "Added timestamp"
          git push
