on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  output_value_job:
    runs-on: ubuntu-latest
    name: Send output
    outputs:  
      anOutputName: ${{ steps.output_step.outputs.my_output }}
    steps:
    - id: output_step
      shell: pwsh
      name: Output variable step
      run: | 
        $myValue = $true
        Write-Host "Logging the output value generated [$myValue]"
        echo "::set-output name=my_output::$myValue"
               
  pick-up-output-value:
    runs-on: ubuntu-latest
    needs: output_value_job
    name: The job that uses the output from the first job
    steps:
    - shell: pwsh
      run: |
        Write-Host "1. The output we got here is [ ${{ needs.output_value_job.outputs.my_output }} ]" 
        Write-Host "2. The output we got here is [ ${{ needs.output_value_job.outputs.output_value }} ]"
        Write-Host "3. The output we got here is [ ${{ needs.output_value_job.outputs.anOutputName }} ]"
    - run: echo ${{ needs.output_value_job.outputs.anOutputName }}
