on:
  push:
    branches: 
      - main
    paths:
    - '**/outputs.yml'
  workflow_dispatch:

# first job generates a value and stores that
# second job uses the stored value

jobs:
  output_value_job:
    runs-on: ubuntu-latest
    name: Send output
    outputs:  
      anOutputName: ${{ steps.output_step.outputs.my_output }}
    steps:
    - id: output_step
      shell: pwsh
      name: Output variable step
      run: | 
        $myValue = $true
        Write-Host "Logging the output value generated [$myValue]"
        echo "::set-output name=my_output::$myValue"
               
  pick-up-output-value:
    runs-on: ubuntu-latest
    needs: output_value_job
    name: The job that uses the output from the first job
    steps:
    - shell: pwsh
      run: |
        Write-Host "The output we got using spaces here is [ ${{ needs.output_value_job.outputs.anOutputName }} ]"
        Write-Host "The output we got NOT using spaces here is [ ${{needs.output_value_job.outputs.anOutputName}} ]"

    - name: Testing in shell using accolades with/without spaces
      run: |
         echo "Output value using spaces =" ${{ needs.output_value_job.outputs.anOutputName }}
         echo "Output value NOT using spaces =" ${{needs.output_value_job.outputs.anOutputName}}
