on:
  push:
  
  workflow_dispatch:


jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: rajbos/actions-testing@v1
      name: Public Action
    
    - uses: rajbos/private-action-test
      name: Private Action
