
on:
  push:
    branches: 
      - main
    paths:
    - '**/testing.yml'
  workflow_dispatch:

# testing running the action inside a container

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: rajbos/actions-testing@v1

  testing-container:
    runs-on: ubuntu-latest
    container: azul/zulu-openjdk-alpine:8-jre
    steps:
      - uses: actions/checkout@v2
        
      - name: What OS is running
        run: uname -a

      - name: What Java version do we have?
        run: java -version